import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", os.urandom(32))

    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Lax"

    REMEMBER_COOKIE_HTTPONLY = True
    REMEMBER_COOKIE_SECURE = True

    PERMANENT_SESSION_LIFETIME = 1800
